### ISSUE TITLE
Error: Invalid room ID

### ISSUE THREAD

**Issue by PickJBennett** [sh4dowb/encrypted-chat#1]
Hello,

I'm very interested in your chat application, but every time I try to connect to a newly-created secure chat room (while testing your live demo), I'm presented with "Error: Invalid room ID"

Here are the contents of the most recent chat page:

Server Status:
Ready

Key Fingerprint:
AB 3C 5B 14 12 6B 1E 45 95 A0 FB 71 74 78 8D 43 66 52 F9 28

Other Party Key Fingerprint:
61 19 FB D6 78 C7 E7 E6 4D 10 B4 C9 E3 82 CF 99 72 62 1E 51 

And here's the URL that was supplied:
https://chat.cagriari.com/#6119FBD678C7E7E64D10B4C9E382CF9972621E51:6626275d1b054a90ebb00084ea358c90

Thanks for your help! :)

**Comment by sh4dowb** [comment]
hi, I just checked and it's working
do you close the first page before trying to connect? if so, don't, open the URL in a new tab

**Comment by PickJBennett** [comment]
> hi, I just checked and it's working
> do you close the first page before trying to connect? if so, don't, open the URL in a new tab

I just tried it again (with the first page closed) both in a new browser on the same phone and also using a completely different phone (though technically the same connection as my phone is tethered by Wi-Fi on the second phone). 🤔

**Comment by sh4dowb** [comment]
> > hi, I just checked and it's working
> > do you close the first page before trying to connect? if so, don't, open the URL in a new tab
> 
> I just tried it again (with the first page closed) both in a new browser on the same phone and also using a completely different phone (though technically the same connection as my phone is tethered by Wi-Fi on the second phone). thinking

I mean **do not close first page**, since it's the first user, and if you close it chat will disconnect

**Comment by PickJBennett** [comment]
Oh, that's fantastic! I got it to work. I think my process was slightly off. 😅 Thank you for your help! 😊
